### ISSUE TITLE
Week 9 (Due Nov. 26) to-do

### ISSUE THREAD

**Issue by LilacHo** [UndefiedCse/Heat-Island#23]
Machine Learning

**Comment by LilacHo** [comment]
Resolution: 0.001 degree circle
- [ ] Aggregate building data (count, mean, sd) @JornsenChao 
- [ ] (Optional) Look for Geographically Weighted Regression @JornsenChao 
- [ ] Prediction phase: User input, exception, test @krittin-kulrat 
- [ ] Training phase @LilacHo 
- [ ] Revise the Readme @LilacHo

**Comment by JornsenChao** [comment]
Are we going to office hour today?

**Comment by LilacHo** [comment]
Yes both of us are here right now.

**Comment by LilacHo** [comment]
@JornsenChao I appreciate your efforts on generating another example. Considering I may update more data points everyday, please don't bother to do this every time when I update. In the same time, could you please collect your code into a <something>.py? For example, I can get the same geojson as you did if I feed my file to the code.

**Comment by JornsenChao** [comment]
Will organize my code
@LilacHo
