### ISSUE TITLE
Week 10 (Due Dec. 3) to-do

### ISSUE THREAD

**Issue by LilacHo** [UndefiedCse/Heat-Island#24]
Machine learning

**Comment by LilacHo** [comment]
- [ ] height_acquire.py @JornsenChao 
- [ ] data_processing.py @JornsenChao 
- [ ] model.py: train the model, save the model @krittin-kulrat  
- [ ] Finalize weather data @LilacHo 
- [ ] Visualization - user friendly @loriwon-uw 
- [ ] Revise all the docs @LilacHo @loriwon-uw

**Comment by LilacHo** [comment]
I can help with the data processing if necessary. Let me know if you need anything from me. @JornsenChao

**Comment by LilacHo** [comment]
I got all the weather data ready. Unfortunately, some of them don't have elevation so I delete the column. @JornsenChao @krittin-kulrat
