### ISSUE TITLE
Last Bit of To-Do's

### ISSUE THREAD

**Issue by loriwon-uw** [UndefiedCse/Heat-Island#68]
- [x] Proper docstrings - please use """ -newline for words- """ i.e. minimum of 3 lines. Also make sure everything has a docstring
- [x] More test cases! Many of our test cases only are the edge cases - we need some one-shot tests too I think (Not all test cases are passing either... What happened? They were passing before?)
- [x] *LW need to finish the first main page; things aren't currently coming together quite right.
- [x] Review the component specs - make sure that I have properly written in your inputs/returns for each of your functions
- [x] Slides
- [x] README.md needs updating. It also needs to include how to run the package. As well as update the directory structure.

**Comment by LilacHo** [comment]
I have reviewed/revised use case 2 in component.

**Comment by LilacHo** [comment]
I have done all the part on my end, including docstring and tests!
